# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('password', models.IntegerField()),
                ('check', models.CharField(default=0, max_length=10)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
