# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
