# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20181119_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2018-11-19'),
            preserve_default=False,
        ),
    ]
