# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_register_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_sculpture', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=30)),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('birthday', models.DateField()),
                ('school', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=11)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.SmallIntegerField(default=0)),
                ('log_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.register')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
