# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=11)),
                ('Sheng_id', models.SmallIntegerField(default=0)),
                ('Shi_id', models.SmallIntegerField(default=0)),
                ('Qu_id', models.SmallIntegerField(default=0)),
                ('Stree_id', models.SmallIntegerField(default=0)),
                ('address_comment', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.SmallIntegerField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.register')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.AlterField(
            model_name='user_info',
            name='head_sculpture',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
