# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20181119_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='head_img',
            field=models.ImageField(default='images/infortx.png', upload_to='head', verbose_name='头像'),
        ),
    ]
