# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_user_info_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='head_img',
            field=models.ImageField(default='images/infortx.png', upload_to='', verbose_name='头像'),
        ),
    ]
