# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20181123_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='Qu_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Sheng_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Shi_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Stree_id',
        ),
        migrations.AddField(
            model_name='address',
            name='Qu',
            field=models.CharField(default=0, max_length=100, verbose_name='区'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='Sheng',
            field=models.CharField(default=0, max_length=100, verbose_name='省'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='Shi',
            field=models.CharField(default=0, max_length=100, verbose_name='市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='Stree',
            field=models.CharField(default=0, max_length=100, verbose_name='街道'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='是否设置为默认'),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_comment',
            field=models.CharField(max_length=200, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='address',
            name='isdelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='address',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.register', verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=30, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='用户号码'),
        ),
        migrations.AlterField(
            model_name='address',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
