# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20181127_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Sheng',
            new_name='hcity',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Qu',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Shi',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Stree',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_comment',
        ),
        migrations.AddField(
            model_name='address',
            name='brief',
            field=models.CharField(default=' ', max_length=255, verbose_name='详细地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='harea',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='省'),
        ),
        migrations.AddField(
            model_name='address',
            name='hproper',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
