# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 14:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20181127_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='harea',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='address',
            name='hproper',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误')], verbose_name='用户号码'),
        ),
    ]
