# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20181130_1456'),
        ('goods', '0002_auto_20181127_1409'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('number', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'order_goods',
            },
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('ordernum', models.CharField(default=0, max_length=255, verbose_name='订单编号')),
                ('name', models.CharField(max_length=30, verbose_name='收货人姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('address', models.CharField(max_length=200, verbose_name='地址信息')),
                ('order_status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '退发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0, verbose_name='订单状态')),
                ('transport', models.CharField(max_length=30, verbose_name='运输方式')),
                ('trans_money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运输金额')),
                ('order_money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='订单商品金额')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='订单总金额')),
                ('real_money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付金额')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='Paymethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('pay_name', models.CharField(max_length=20, verbose_name='支付方式')),
                ('logo', models.ImageField(upload_to='pay/', verbose_name='logo')),
            ],
            options={
                'verbose_name': '支付方式',
                'verbose_name_plural': '支付方式',
                'db_table': 'paymethod',
            },
        ),
        migrations.AddField(
            model_name='order_info',
            name='paymethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Paymethod', verbose_name='支付方式id'),
        ),
        migrations.AddField(
            model_name='order_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.register', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='order_goods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order_info', verbose_name='订单id'),
        ),
        migrations.AddField(
            model_name='order_goods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='商品sku_id'),
        ),
    ]
