# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181130_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
