# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('comment', models.CharField(max_length=200, verbose_name='活动描述')),
                ('order', models.IntegerField(verbose_name='排序')),
                ('is_up', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'db_table': 'actarea',
            },
        ),
        migrations.CreateModel(
            name='Actgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('actarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Actarea', verbose_name='活动专区id')),
            ],
            options={
                'db_table': 'actgoods',
            },
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('img', models.ImageField(default='goods/s2.png ', upload_to='goods/%Y%m', verbose_name='图片地址')),
                ('url', models.CharField(max_length=200, verbose_name='跳转的界面地址')),
            ],
            options={
                'db_table': 'active',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='轮播名称')),
                ('img', models.ImageField(default='goods/banner.png ', upload_to='goods/%Y%m', verbose_name='图片地址')),
                ('order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'db_table': 'ad',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('catename', models.CharField(max_length=30, verbose_name='分类名')),
                ('comment', models.TextField(verbose_name='分类描述')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('img', models.ImageField(default='goods/pic.png ', upload_to='goods/%Y%m', verbose_name='商品图片地址')),
            ],
            options={
                'db_table': ' goodsimg',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('introduction', models.TextField(verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('unit', models.SmallIntegerField(choices=[(1, '斤'), (2, '件'), (3, '箱')], verbose_name='单位')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('sell', models.IntegerField(verbose_name='销量')),
                ('img', models.ImageField(default='goods/s2.png ', upload_to='goods/%Y%m', verbose_name='图片logo地址')),
                ('is_up', models.BooleanField(default=True, verbose_name='是否上架')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='分类id')),
            ],
            options={
                'db_table': 'SKU',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='spu名称')),
                ('content', models.TextField(verbose_name='商品详情')),
            ],
            options={
                'db_table': 'SPU',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPU', verbose_name='spu_id'),
        ),
        migrations.AddField(
            model_name='goodsimg',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='sku_id'),
        ),
        migrations.AddField(
            model_name='ad',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='商品规格id'),
        ),
        migrations.AddField(
            model_name='active',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='关联表id'),
        ),
        migrations.AddField(
            model_name='actgoods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='商品id'),
        ),
    ]
