# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 14:09
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actarea',
            options={'verbose_name': '活动专区', 'verbose_name_plural': '活动专区'},
        ),
        migrations.AlterModelOptions(
            name='actgoods',
            options={'verbose_name': '活动专区商品', 'verbose_name_plural': '活动专区商品'},
        ),
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': '商品活动表', 'verbose_name_plural': '商品活动表'},
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.AlterModelOptions(
            name='goodsimg',
            options={'verbose_name': '商品相册表', 'verbose_name_plural': '商品相册表'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name': '商品SKU表', 'verbose_name_plural': '商品SKU表'},
        ),
        migrations.AlterModelOptions(
            name='spu',
            options={'verbose_name': '商品SPU表', 'verbose_name_plural': '商品SPU表'},
        ),
        migrations.AlterField(
            model_name='active',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='sku_id'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='sku_id'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情'),
        ),
    ]
